### ISSUE TITLE
waitForAngularRequestsToFinish taking very long time

### ISSUE THREAD

**Issue by sunnysachdeva** [paul-hammant/ngWebDriver#32]
waitForAngularRequestsToFinish() for site http://www.sephora.com/ is taking very long time. I dont know if this site specific issue or something wrong with this function. Is there any way I can check manually if angular calls have been processed.

**Comment by emanlove** [comment]
I have some javascript that I used in exploring and explaining what is going on within Protractor. You could paste the following into the console editor (Under Firefox/Firebug open developer tools (F12) > Console Tab > Show Console Editor or little up red arrow square)

```javascript
var callback = function () {console.log('*')}
var el = document.querySelector('#nested-ng-app');
var h = setInterval(function w4ng() {
    console.log('.');
    try {
        angular.element(el).injector().get('$browser').
            notifyWhenNoOutstandingRequests(callback);
    } catch (err) {
      console.log(err.message);
      callback(err.message);
    }
  }, 10);
```
You may need to replace the querySelector ```#nested-ng-app``` with the angular root element on you site.

This will output a constant fluctuation between . and * when Angular is not waiting. The when the page is in a state of waiting for Angular a constant series of . and then a series of *. This will at least get you a chance to manually inspect the site and see if what you are expecting is the same as what is happening.

Note when you want to stop the output above you should type in

```javascript
clearInterval(h);
```

**Comment by sunnysachdeva** [comment]
When I ran the above JS i kept on getting series of "*."
Does it means something is wrong with my application. Is it taking long time for angular calls?

**Comment by emanlove** [comment]
No the continuous stream of "*"s and "."s means that for the most part there is not a backlog, if you will, of angular promises and that waitForAngular shouldn't be waiting. Note for the site you noted, www.sephora.com/, I had to change the query selector to ```[ng-app]``` as in 

```javascript
var el = document.querySelector('[ng-app]');
```

otherwise I was seeing an ```angular.element(...).injector(...) is undefined error```. To see the change in output above and see where waitForAngular should wait navigate on you site to one of the products pages and for which there is a lot of products. Then manually scroll to the bottom. With the above code running click on the "Top" link. Now you should see only "."s printed as the web app scrolls you to the top.

**Comment by emanlove** [comment]
@sunnysachdeva: If it is still taking a long amount of time you might make a small unit test case to show and demonstrate what you are doing and what response you are getting.

**Comment by paul-hammant** [comment]
Switch to a classic waitFor() strategy for something in the page (or gone from the page) being a result of Angular finished.

All we do is copy browser-side Protractor's JavaScript, and we're fully up to date here.
